"""Evaluation guide tab for Streamlit UI."""

import streamlit as st


def render_evaluation_guide_tab() -> None:
    """Render the evaluation guide for beginners."""
    st.header("Evaluation Guide & Metrics Interpretation")
    st.markdown("""
    When evaluating an anomaly detection model in an industrial setting, classical metrics like **Accuracy**
    can be incredibly misleading. This guide explains exactly how to read the metrics generated by the pipelines.

    ---

    ### 1. The Accuracy Paradox
    In industrial manufacturing, anomalies are rare (e.g., 99% of components are good, 1% are defective).
    If a "dummy" model blindly guesses that **every** component is good, it will achieve **99% Accuracy**.
    - **Why it's bad:** The model entirely missed the 1% of defective parts, rendering it useless for quality control.
    - **Takeaway:** Never trust Accuracy alone when evaluating an anomaly detection model.

    ---

    ### 2. Precision and Recall
    These metrics give you a clearer picture than Accuracy, especially when dealing with rare defects.
    - **Precision:** Out of all the components the model *flagged* as defective, how many were *actually* defective?
      - *High Precision = Very few false alarms.*
    - **Recall:** Out of all the *actually* defective components, how many did the model successfully *flag*?
      - *High Recall = Very few escaped defects (missed anomalies).*

    In industry, we usually prioritize **Recall** (we cannot let a broken part reach a customer).
    However, if Precision is too low, the operator will be overwhelmed with false alarms and might turn the system off.

    ---

    ### 3. AUROC (Area Under the Receiver Operating Characteristic Curve)
    *Used for: Image-Level Evaluation (Is the entire component defective or not?)*

    The AUROC score measures how well the model separates the "Good" scores from the "Defective" scores
    across *all possible threshold values*.

    **⚠️ The Imbalance Trap:**
    In real factories, 99.9% of components are good, and 0.1% are bad. In such extreme class imbalances, AUROC
    is notoriously deceptive. A model can achieve a 0.95 AUROC but still have a terrible Precision (firing false
    alarms constantly) because the massive number of True Negatives drowns out the False Positives.

    **Why do we still use it?**
    1. **Benchmarking:** Academic test sets (like MVTec AD) artificially balance the test images (e.g.,
       20 good, 60 bad), making Image-Level AUROC acceptable for literature comparison.
    2. **Top-K Pooling:** We do not use the maximum pixel error as the image score. Max-pooling fails because
       a single dead camera pixel causes a false positive. We use **Top-K Pooling** (averaging the worst ~30
       pixels), which ensures the image score reflects a *cluster* of defects, making the Image-Level AUROC
       much more robust to noise.

    *For real-world deployment, rely on **F1-Score** or **PR-AUC** (Precision-Recall AUC) instead of AUROC.*

    ### 4. AUPIMO (Area Under Per-Image Overlap)
    *Used for: Pixel-Level Evaluation (Where exactly is the defect on the component?)*

    Standard pixel evaluation metrics (like PRO-score) evaluate the model up to a 30% False Positive Rate (FPR).
    In an industrial factory making 10,000 parts a day, a 30% false alarm rate means throwing away
    3,000 perfect components. This is unacceptable.

    **AUPIMO** measures how well the model isolates defective pixels under extremely strict,
    realistic industrial constraints (FPR between 1e-5 and 1e-4).
    - **FPR 1e-5:** Equals 1 false alarm per 100,000 normal parts.
    - **What a Good Score Looks Like:** Because the FPR restriction is so brutal, AUPIMO scores are
      naturally lower than AUROC. A score above `0.20` is considered excellent, and anything above `0.05`
      is generally highly usable for precise localization.
    """)
